server:
  port: 6060
  forward-headers-strategy: framework
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  flyway:
    baseline-on-migrate: true
  application:
    name: kronify-apis
  config:
    import: optional:file:.env[.properties]
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - openid
              - email
              - profile
          azure:
            client-id: ${OAUTH_MICROSOFT_CLIENT_ID}
            client-secret: ${OAUTH_MICROSOFT_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/azure"
            scope:
              - openid
              - email
              - profile
        provider:
          azure:
            authorization-uri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/common/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
            user-name-attribute: sub
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-minutes: ${JWT_EXPIRATION_MINUTES}
  frontend-url: ${FRONTEND_URL}
  upload:
    path: ${UPLOAD_DIR:./uploads}
  admin:
    api-key: ${ADMIN_API_KEY}
