server:
  port: 6060
  forward-headers-strategy: framework
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  flyway:
    baseline-on-migrate: true
  application:
    name: kronify-apis
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-minutes: ${JWT_EXPIRATION_MINUTES}
  frontend-url: ${FRONTEND_URL}
  upload:
    path: ${UPLOAD_DIR:./uploads}
  admin:
    api-key: ${ADMIN_API_KEY}
